In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("titanic_survivor.csv")

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
#AS IN THE ABOVE COLUMN IAM DROPPING THE USELESS DATA SO THAT IT WILL BE EASY FOR ME TO PROCESS THE DATA
data.drop(['Name','Parch','Embarked','SibSp','Ticket','Cabin','PassengerId'],axis='columns',inplace=True)

In [5]:
data.head(1)

Survived  Pclass   Sex   Age  Fare
0         0       3  male  22.0  7.25

In [6]:
#now set the target and input values seperatetly in order to train and split the data
targets=data.Survived
inputs=data.drop("Survived",axis="columns")
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [7]:
inputs.Sex=inputs.Sex.map({"male":1,"female":0}).astype(int)
inputs

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [8]:
inputs

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [9]:
inputs.isna().any()

Pclass    False
Sex       False
Age        True
Fare      False
dtype: bool

In [10]:
inputs.Age.head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [11]:
#now fill na value with mean 
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.Age.head(10)

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

In [12]:
targets.head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(inputs,targets,test_size=0.30,random_state=42)

In [14]:
inputs.shape

(891, 4)

In [15]:
X_train.shape

(623, 4)

In [16]:
X_test.shape

(268, 4)

In [17]:
y_test.shape

(268,)

In [18]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [19]:
model.fit(X_test,y_test)

GaussianNB()

In [20]:
model.predict(X_test[:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [21]:
model.score(X_test,y_test)

0.7873134328358209

In [22]:
X_test[:10]

Pclass  Sex        Age     Fare
709       3    1  29.699118  15.2458
439       2    1  31.000000  10.5000
840       3    1  20.000000   7.9250
720       2    0   6.000000  33.0000
39        3    0  14.000000  11.2417
290       1    0  26.000000  78.8500
300       3    0  29.699118   7.7500
333       3    1  16.000000  18.0000
208       3    0  16.000000   7.7500
136       1    0  19.000000  26.2833

In [23]:
y_test[:10]

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: Survived, dtype: int64

In [24]:
model.predict(X_test[:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [25]:
model.predict_proba(X_test[:10])

array([[0.9610635 , 0.0389365 ],
       [0.91080197, 0.08919803],
       [0.95849052, 0.04150948],
       [0.13057108, 0.86942892],
       [0.32849171, 0.67150829],
       [0.01161806, 0.98838194],
       [0.36277897, 0.63722103],
       [0.955236  , 0.044764  ],
       [0.3338798 , 0.6661202 ],
       [0.0429398 , 0.9570602 ]])

In [31]:
y_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
accuracy*100

78.73134328358209